### ISSUE TITLE
Edit tasks

### ISSUE THREAD

**Issue by KivancUlucan** [KivancUlucan/Capstone-Project#12]
## Value proposition

As a user
I want to be able to edit the tasks
In order to keep them up to date

## Description

![Image](https://github.com/KivancUlucan/Capstone-Project/assets/117660396/9ba0713a-900f-4dfd-bc4f-f9426cf81752)

## Acceptance criteria

- [ ] Edit buttons visible on all tasks 
- [ ] Click on edit button lets the user change the input-fields

## Tasks

- [ ] Create a new branch
- [ ] Add edit buttons with according functionality
