### ISSUE TITLE
Layout 

### ISSUE THREAD

**Issue by KivancUlucan** [KivancUlucan/Capstone-Project#3]
## Value proposition

As a user 
I want to see a header that contains the logo of the app and a footer that contains the links "Summary", "Bord" and "Add Task" so I can click the links later on

## Description

![image](https://user-images.githubusercontent.com/117660396/234552389-2ac11037-8c00-489d-8c23-813135e853e1.png)

## Acceptance criteria

- [ ] Header and Footer are visible all the time
- [ ] Header contains a Logo
- [ ] Footer contains the Links: "Summary", "Board", "Add Task", which are not clickable yet

## Tasks

- [ ] Create a branch
- [ ] Create and add the components: "Header" and "Footer"
- [ ] Add styling

**Comment by NikRoe** [comment]
Hi Kivanc,

your first user story should already provide your users with some benefits. Having links that don't work yet, is not a good user experience. You should also implement links that lead to actual pages.

I would recommend you start with the add task functionality and display the tasks after submitting them.
This will directly give your users something they can interact with. 

The value proposition could be:
As a user,
I want to add tasks,
to be able to track them.

Your wireframe would show the form with which new tasks can be submitted and you would also have a wireframe that shows where a submitted task would be appear.

Please consider making this your first user story :)

**Comment by NikRoe** [comment]
This looks very nice 👍 

Only one minor question is left to be answered: After submitting a new task, will the task be shown below the form or will it be shown on a different page?

You should answer this in your user story and once you have done this, you are good to proceed 🙌
