### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by KivancUlucan** [KivancUlucan/Capstone-Project#4]
## Value proposition

As a user,
i want to see a Header and a Footer over all pages and want to be able to go to the respective pages by clicking the links to have a better experience

## Description

![image](https://user-images.githubusercontent.com/117660396/234624781-d5a68aec-214d-4d1b-94a2-2e1a9adb861e.png)

## Acceptance criteria

- [ ] Header and Footer are fixed and visible over all pages.
- [ ] The links work and lead to the respective pages

## Tasks

- [ ] Create a branch
- [ ] Create the component "Header", containing the logo 
- [ ] Create the component "Footer", containing the links
- [ ] Make the links work

**Comment by t0bbl** [comment]
looks good :)
