### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by KivancUlucan** [KivancUlucan/Capstone-Project#5]
## Value proposition

As a user,
i want to be able, to see all the tasks displayed as a total overview 
in order to to keep track of them all.

## Description

![Image](https://github.com/KivancUlucan/Capstone-Project/assets/117660396/d63cdd46-cd28-4646-bf1c-81aec013c4d7)

## Acceptance criteria

- [ ] Each group of tasks (backlog, in progress, awaiting feedback and done) is displayed as a box

## Tasks

- [ ] Create a branch
- [ ] Create the component "Summary"
- [ ] Create a card displaying each group of task as a box

**Comment by t0bbl** [comment]
i dont know if you need the text "kanban project management tool" in the first wireframe but thats just a minor detail. looks good otherwise!
